### ISSUE TITLE
App looks like it's doing nothing on initial load

### ISSUE THREAD

**Issue by CrackLord** [pmaji/eth_python_tracker#11]
I've been wondering how to fix this myself but I don't know enough about these libraries to figure it out. When you load the app it looks like it's doing nothing for 10 seconds until it makes the first requests to the server to get the data.

It seems to be because of the interval being set to 10 seconds, it waits for the first 10 seconds to tick and then it loads the data. What would be better is if it loaded the graphs immediately on the page's first load and then updated them every 10 seconds, but I can't see how to do this from the library being used.

**Comment by pmaji** [comment]
That's a good point. I think it is difficult to accomplish this given that we moved the data loan to be done behind the scenes to prevent refresh overload. 

I'll see if maybe there is a way I can get a loading modal to pop up or something that signals that it is loading, but tbh I don't immediately know of a solution.

**Comment by JaTochNietDan** [comment]
> I think it is difficult to accomplish this given that we moved the data loan to be done behind the scenes to prevent refresh overload.

Actually since we did that, you could probably just change the timeout to be much lower since it won't put any real load on the server since it's just serving data from memory now.

Changing the update interval to 2 seconds or should be fine.

**Comment by CrackLord** [comment]
Actually since we did that, you could probably just change the timeout to be much lower since it won't put any real load on the server since it's just serving data from memory now.

Changing the update interval to 2 seconds or should be fine.

**Comment by pmaji** [comment]
Yep. Just tested it and I think 2 second is a happy medium so that there's still enough time for tool-tips to be read. I've updated master to use the 2 second load time. Closing this issue now :)
