### ISSUE TITLE
Adding visual call-outs for high order count vs. low order count

### ISSUE THREAD

**Issue by pmaji** [pmaji/eth_python_tracker#12]
Taken from a reddit comment; should be able to do something like this:

"Can you put perhaps a thin black stroke around the circles that are controlled by say under 5 addresses and perhaps a thick one around 1 address? Also a small written text of the price really close would be great - hoovering the mouse and it going in less than 2 seconds is hard to keep track of when they’re moving. Thanks excellent tool."

**Comment by pmaji** [comment]
Completed; now the coloring differentiates between price-points with 5 or more distinct orders behind it.

**Comment by theimo1221** [comment]
Possible future improvement in #27
