### ISSUE TITLE
Adding ETHBTC ratio

### ISSUE THREAD

**Issue by arsenicks** [pmaji/eth_python_tracker#2]
[appv0.1.txt](https://github.com/pmaji/eth_python_tracker/files/1684175/appv0.1.txt)

Hi, I'm no way near a coder, just a sysadmin debugging perl/python/bash code sometimes. I was playing around to see if I was able to add the ethbtc chart, I think I got it.( Don't really understand the details, it's all copy pasta from your code ;) )

Feel free to take a look and adapt it if you want to merge in the code!

Thanks again for sharing!

**Comment by pmaji** [comment]
Wonderful contribution @arsenicks! Just for giving it a quick one-over I think the pull should work; the details will probably need refining surrounding the div integration itself (making it fit and look pretty on most standard browsers), but I will definitely look to integrate this in the near future and will let you know when it gets resolved. Really appreciate the collaboration!

**Comment by pmaji** [comment]
@arsenicks I just read over the code. Perfectly well done. The layout hasn't been fixed yet so it all fits snugly (you now have to scroll) but that is a problem for another time--I'll probably just have to get fancier with my div definitions, so I can get to that later. Important thing is it's operational! Appreciate the contribution again!
