### ISSUE TITLE
Few ideas and questions

### ISSUE THREAD

**Issue by arsenicks** [pmaji/eth_python_tracker#4]
* Add a link to the bottom of the page linking to the github
* Add a slider to adjust the refresh time
* Permit to add dynamically new charts, as we saw, the only thing to change is the eth-btc or eth-usd to get bch-usd etc... It shouldn't be too hard to re-use the code and let user add charts with a button
* If we could add new charts/pair add a save button and just save the config so we won't loose anything if we stop the app.
* Adjust the size of the circles size when zoomed in the graph, it's hard to see when you zoom on the small order!

Q.
* I was trying to find documentation regarding the column address you request in the code, what does it return ? In the description you said the app allow us to see if walls are from one person of few person right ? In the graph X axis is the price Y the order size, how can I see if the big red circle with a sell order size of 350 and at a price of 815 is only one whale or few others players ? I can only see a circle, what if a guy set a sell order at 815 for 200 and and another one at the same price for 150, how can I see these are two different person/order ?

Thanks!

**Comment by pmaji** [comment]
All good questions @arsenicks! I'll look into them when I can. I think your last question sparks a good point, in that I can see it in the raw data, but it's not immediately obvious from the visual. Maybe I can scale the color relative to the ETH address, which could make an impact. I'll play around with it here shortly.

**Comment by pmaji** [comment]
So I just looked over the code again @arsenicks, and the separation by ETH address is being done, but implicitly. So what I mean by that is if you look at the orders (this is easier to see with smaller than with larger orders) there are many set at the same price (right now I see a bunch at $835), but all of them have different volume. This is how you can distinguish between 1 vs. multiple orders. That said, you could theoretically have a whale that sets multiple orders at the same price but for different volume, which would essentially mess up the utility of my methodology. I'm thinking of going the selective-coloring route, and will work on that now for a bit, but let me know if you have other ideas.

**Comment by pmaji** [comment]
Ok @arsenicks ; I **just fixed what I consider to be the most important thing you called-out; the ability to always distinguish between distinct users behind a particular order.** I tried a bunch of different solutions, from making the plot 3-D, to altering the selective coloring, to adding labels, but I went with the addition of a helpful tool tip instead. 

**This new addition handles for the rare case where multiple ETH addresses submit orders of equal price and equal volume. For example, if 2 users both submit orders at a price of $1000 for 250 ETH, this would presently show up as a bubble of 500 ETH for $1000, but that is partially misleading. Now, the user can hover over that particular bubble and, thanks to the tool-tip, see the exact number of distinct addresses.**

Your other suggestions are also really helpful, and I hope to be able to devote time to them soon, unless a good GitHub Samaritan can lend a hand. I would amend your list as follows:

- Add a link to the bottom of the page linking to the GitHub **(agree entirely)**
- Add a slider to adjust the refresh time **(Given new additions and potentially increased complexity in the future, I think instead I would like to go with a button refresh that the user can click)**
- Dynamically add new charts **(This is a great idea, but also magnitudes more complicated than what I have presently. I think the next stage of evolution of this project would instead be a drop-down menu where the user can select what chart they want to see, etc., but a create-your-own type menu would require that I make the entire code in function form, where the arguments are input by the user, and that would take a lot more of my time)**
- Adjusting the size on zoom **(Agree entirely. Particularly if I go the route of a manual refresh button, this will be important. I don't know how to do it off the top of my head, but I'll try to look into it.)**

**Comment by arsenicks** [comment]
Oh nice update for the tool tip, it's easy to catch them now!

As I said before I'm not really a programmer so I can't help a lot with the new feature, but I'll see if I find some time and patience to learn and help ;) I just wanted to share some ideas hoping someone with more knowledge with help advance the project!

**Comment by pmaji** [comment]
@arsenicks no worries! I actually fixed a lot of them already! I think the zoom in is the only one I haven't addressed quite yet and there are a few new ones I added based on Reddit feedback :) I've gotten some more help from some generous contributors and the project is growing very fast :)

**Comment by theimo1221** [comment]
- [x] Link to Github in #26  
- [x] Made adding charts more modular in #24 
- [ ] Add Button for refresh
- [ ] Add Dropdown/ Radio Button for selecting graphs
- [ ] Adjusting the size on zoom

**Comment by pmaji** [comment]
@arsenicks the hardest one of these has now been taken care off -- the freeze button now implemented lets the user pause the refreshes so that the utility of the plotly hover-over is preserved.

**Comment by pmaji** [comment]
Going to close this now because all remaining questions have been opened as their own issues.
