### ISSUE TITLE
Rework legend

### ISSUE THREAD

**Issue by theimo1221** [pmaji/eth_python_tracker#45]
- [x] Logscale
- [x] Color Description
- [x] Show/ Hide Buttons
- [x] Filtering on low volume

**Comment by pmaji** [comment]
@theimo1221 
Will take care of this and also integrate into the README asap.
I think only thing that would be helpful to have from your perspective on this is a description of how the low volume orders are filtered out for the final visualization. Then I can write up a plain english version for the readme.

**Comment by pmaji** [comment]
All issues taken care of and integrated into the legend.
